
from __future__ import annotations

import argparse
import time
from pathlib import Path

import pandas as pd
from scipy import stats

from config import PATHS, STIMULUS_SEVERITY_COLUMN
from src import plot_style
from src.instrument.storage import load_responses
from src.plot_style import BLUE, INK, INK_2, MUTED, RED

# primary regressor, text-modality robustness check, weight-sensitivity check
REGRESSORS = [STIMULUS_SEVERITY_COLUMN, "severity_text", "severity_vision_alt"]

SYNTH_BANNER = "⚠ **SYNTHETIC DATA — SIMULATED PARTICIPANTS, NOT HUMAN RESULTS**"


def compute_deltas(responses: pd.DataFrame, stimuli: pd.DataFrame) -> pd.DataFrame:
    """Per screen: decision rate per condition and the behavioral delta
    (manipulated minus neutralized). Requires both conditions per screen."""
    rates = (
        responses.groupby(["screen_id", "condition"])["decision"]
        .agg(["mean", "count"])
        .unstack("condition")
    )
    for cond in ("manipulated", "neutralized"):
        if ("mean", cond) not in rates.columns:
            raise RuntimeError(f"no responses at all in condition {cond!r}")
    rates = rates[rates["mean"].notna().all(axis=1)]

    deltas = pd.DataFrame({
        "screen_id": rates.index,
        "rate_manipulated": rates[("mean", "manipulated")].to_numpy(),
        "rate_neutralized": rates[("mean", "neutralized")].to_numpy(),
        "n_manipulated": rates[("count", "manipulated")].astype(int).to_numpy(),
        "n_neutralized": rates[("count", "neutralized")].astype(int).to_numpy(),
    })
    deltas["delta"] = deltas["rate_manipulated"] - deltas["rate_neutralized"]

    merged = deltas.merge(
        stimuli[["screen_id"] + REGRESSORS], on="screen_id", how="inner"
    )
    if len(merged) < 3:
        raise RuntimeError(
            f"only {len(merged)} screens have responses in both conditions "
            f"and a severity score — need >= 3 for a regression"
        )
    return merged.sort_values(STIMULUS_SEVERITY_COLUMN).reset_index(drop=True)


def run_regressions(deltas: pd.DataFrame) -> dict:
    results = {}
    for col in REGRESSORS:
        fit = stats.linregress(deltas[col], deltas["delta"])
        results[col] = {
            "slope": fit.slope,
            "intercept": fit.intercept,
            "r2": fit.rvalue ** 2,
            "p_value": fit.pvalue,
            "stderr": fit.stderr,
            "n_screens": len(deltas),
        }
    return results


def _plot(deltas: pd.DataFrame, res: dict, synthetic: bool, out_path: Path) -> None:
    fig, ax = plot_style.new_axes()
    x = deltas[STIMULUS_SEVERITY_COLUMN]
    ax.scatter(x, deltas["delta"], s=70, color=BLUE, zorder=3)
    for r in deltas.itertuples():
        ax.annotate(r.screen_id, (getattr(r, STIMULUS_SEVERITY_COLUMN), r.delta),
                    xytext=(6, 4), textcoords="offset points",
                    fontsize=6.5, color=MUTED)

    prim = res[STIMULUS_SEVERITY_COLUMN]
    xs = [x.min(), x.max()]
    ax.plot(xs, [prim["intercept"] + prim["slope"] * v for v in xs],
            color=BLUE, linewidth=2, zorder=2)
    ax.annotate(
        f"slope {prim['slope']:.3f} · R² {prim['r2']:.3f} · p {prim['p_value']:.2g}",
        xy=(0.03, 0.95), xycoords="axes fraction",
        fontsize=9, color=INK_2, va="top",
    )
    ax.set_xlabel(f"{STIMULUS_SEVERITY_COLUMN} (model score, fixed pre-experiment)",
                  color=INK_2)
    ax.set_ylabel("behavioral delta (manipulated − neutralized decision rate)",
                  color=INK_2)
    ax.set_title("Does severity predict decision change?", color=INK, fontsize=12)

    if synthetic:
        ax.text(0.5, 0.5, "SYNTHETIC", transform=ax.transAxes,
                fontsize=52, color=RED, alpha=0.22, rotation=30,
                ha="center", va="center", zorder=1)
        fig.text(0.5, 0.965, "SYNTHETIC DATA — SIMULATED PARTICIPANTS, NOT HUMAN RESULTS",
                 ha="center", fontsize=9, color=RED, weight="bold")
    plot_style.save(fig, out_path)


def _write_md(deltas: pd.DataFrame, res: dict, responses: pd.DataFrame,
              synthetic: bool, out_path: Path) -> None:
    src_counts = responses["source"].value_counts().to_dict()
    prim = res[STIMULUS_SEVERITY_COLUMN]
    text_r = res["severity_text"]
    alt_r = res["severity_vision_alt"]

    md = []
    if synthetic:
        md += [f"> {SYNTH_BANNER}", ">",
               "> Responses were generated by `src/synthetic_participants.py` "
               "with a planted effect; this report validates the apparatus, "
               "not any hypothesis about people.", ""]
    md += [
        "# Severity vs behavior",
        "",
        f"Generated {time.strftime('%Y-%m-%d %H:%M')} · "
        f"{len(responses)} responses ({src_counts}) · "
        f"{deltas['n_manipulated'].sum() + deltas['n_neutralized'].sum()} used "
        f"across {len(deltas)} screens",
        "",
        "Per screen: behavioral delta = decision rate under the manipulated "
        "screen minus under its neutralized counterpart. The delta is "
        "regressed on the screen's severity score (fixed before any behavior "
        "was collected).",
        "",
        "## Regressions",
        "",
        "| regressor | role | slope | R² | p | n screens |",
        "|---|---|---|---|---|---|",
        f"| {STIMULUS_SEVERITY_COLUMN} | **primary** (the claim under test) | "
        f"{prim['slope']:.3f} | {prim['r2']:.3f} | {prim['p_value']:.2g} | "
        f"{prim['n_screens']} |",
        f"| severity_text | robustness (text modality) | {text_r['slope']:.3f} | "
        f"{text_r['r2']:.3f} | {text_r['p_value']:.2g} | {text_r['n_screens']} |",
        f"| severity_vision_alt | weight sensitivity (other=0.9) | "
        f"{alt_r['slope']:.3f} | {alt_r['r2']:.3f} | {alt_r['p_value']:.2g} | "
        f"{alt_r['n_screens']} |",
        "",
        "## Per-screen deltas",
        "",
        "| screen_id | severity_vision | rate manip | rate neutral | delta | "
        "n manip | n neutral |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in deltas.itertuples():
        md.append(
            f"| {r.screen_id} | {getattr(r, STIMULUS_SEVERITY_COLUMN):.3f} | "
            f"{r.rate_manipulated:.3f} | {r.rate_neutralized:.3f} | "
            f"{r.delta:+.3f} | {r.n_manipulated} | {r.n_neutralized} |"
        )

    agree = (prim["slope"] > 0) == (text_r["slope"] > 0)
    md += [
        "",
        "## Reading the result",
        "",
        f"- Primary: severity_vision "
        f"{'predicts' if prim['p_value'] < 0.05 else 'does NOT significantly predict'} "
        f"the behavioral delta (slope {prim['slope']:.3f}, p {prim['p_value']:.2g}).",
        f"- The text-severity robustness check "
        f"{'agrees in sign' if agree else 'DISAGREES in sign'} "
        f"(slope {text_r['slope']:.3f}, p {text_r['p_value']:.2g}).",
        f"- Under the alt potency weights the slope is {alt_r['slope']:.3f} "
        f"(p {alt_r['p_value']:.2g}) — "
        f"{'conclusions are stable across the weight choice.' if (alt_r['p_value'] < 0.05) == (prim['p_value'] < 0.05) else 'significance CHANGES with the weight choice; state both.'}",
        "",
        "![severity vs behavior](severity_vs_behavior.png)",
        "",
    ]
    if synthetic:
        md += [f"> {SYNTH_BANNER}", ""]
    out_path.write_text("\n".join(md))


def run_analysis(
    responses_path: Path | None = None,
    stimuli_path: Path | None = None,
    out_dir: Path | None = None,
) -> dict:
    """Full pipeline: responses + stimuli -> deltas -> regressions -> report.
    Returns the regression results dict (used by the end-to-end test)."""
    out_dir = Path(out_dir) if out_dir is not None else PATHS["reports"]
    out_dir.mkdir(parents=True, exist_ok=True)

    responses = load_responses(responses_path)
    stimuli = pd.read_csv(stimuli_path if stimuli_path is not None else PATHS["stimuli"])

    # one synthetic row anywhere marks the whole report as synthetic
    synthetic = bool((responses["source"] == "synthetic").any())

    deltas = compute_deltas(responses, stimuli)
    res = run_regressions(deltas)

    _plot(deltas, res, synthetic, out_dir / "severity_vs_behavior.png")
    _write_md(deltas, res, responses, synthetic, out_dir / "severity_vs_behavior.md")

    prim = res[STIMULUS_SEVERITY_COLUMN]
    tag = "SYNTHETIC" if synthetic else "human"
    print(
        f"[analysis] ({tag}) slope {prim['slope']:.3f}, R² {prim['r2']:.3f}, "
        f"p {prim['p_value']:.2g} over {prim['n_screens']} screens -> "
        f"{out_dir / 'severity_vs_behavior.md'}"
    )
    return res


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--responses", type=Path, default=None)
    ap.add_argument("--stimuli", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args()
    run_analysis(args.responses, args.stimuli, args.out_dir)


if __name__ == "__main__":
    main()
